ARCH:
  INPUT_SIZE: [64, 64]
  FILTERS: [16, 32, 64]

DATA:
  IM_DIR: dataset/real_data
  DIST_PATH: dataset/real_data/labels.json
  TEST_SIZE: 0.9
  GRAYSCALE: True

TRAIN:
  LR: 0.001
  DECAY: 0.000005
  LOSS: mean_absolute_percentage_error
  EPOCHS: 200
  BATCH_SIZE: 32
  SAVE_PATH: weights
  LOGS_PATH: logs/train

TEST:
  WEIGHTS: weights/20191129-13555663.h5
  LOGS_PATH: logs/test
